# Generated by Django 3.2.5 on 2021-07-04 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('section', models.CharField(max_length=120)),
                ('subject', models.CharField(max_length=120)),
                ('room', models.CharField(max_length=120)),
                ('class_code', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=120)),
                ('Lname', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=50)),
                ('AccountType', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='profilePic/')),
                ('Password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=120)),
                ('Lname', models.CharField(max_length=120)),
                ('Email', models.EmailField(max_length=50)),
                ('AccountType', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='profilePic/')),
                ('Password', models.TextField()),
                ('classJoin', models.ManyToManyField(to='class.Class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacherId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.teacher'),
        ),
    ]
