# Generated by Django 3.2.6 on 2021-08-28 17:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='readingtimeImage\\')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pageNo', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('reviewId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='class.readingreview')),
            ],
        ),
    ]
