# Generated by Django 3.2.5 on 2021-07-10 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='material/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.class')),
            ],
        ),
    ]
