# Generated by Django 3.2.6 on 2021-09-01 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingreview',
            name='status',
        ),
        migrations.AddField(
            model_name='readingreview',
            name='comTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
