# Generated by Django 3.2.6 on 2021-09-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_auto_20210901_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingreview',
            name='status',
            field=models.CharField(default='incomplete', max_length=20),
        ),
        migrations.AlterField(
            model_name='readingreview',
            name='comTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
