# Generated by Django 3.2.6 on 2021-09-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_auto_20210902_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingreview',
            name='comTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
