# Generated by Django 3.2.5 on 2021-08-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_audioquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestion',
            name='AudioQuestion',
            field=models.FileField(blank=True, upload_to='AudioQustion/'),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
