# Generated by Django 3.2.6 on 2021-08-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_auto_20210801_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestion',
            name='left',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='top',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='textquestion',
            name='width',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
