# Generated by Django 4.0 on 2022-06-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0006_auto_20210913_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(default='T9Vh9atd', max_length=120),
        ),
    ]
