# Generated by Django 3.2.6 on 2021-08-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0007_auto_20210818_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textquestion',
            name='left',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='top',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='textquestion',
            name='width',
            field=models.TextField(blank=True),
        ),
    ]
