# Generated by Django 4.1 on 2022-11-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0010_alter_class_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(default='93n5B5Qg', max_length=120),
        ),
    ]
