# Generated by Django 4.1 on 2022-12-25 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0011_alter_class_class_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(default='ua0bzEUS', max_length=120),
        ),
    ]
