# Generated by Django 4.1 on 2022-12-25 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0012_remove_question_student_id_alter_class_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(default='KGBSAoWB', max_length=120),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_no', models.IntegerField()),
                ('answer', models.TextField(blank=True)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.question')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.student')),
            ],
        ),
    ]
