# Generated by Django 4.1 on 2022-12-25 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0013_alter_class_class_code_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(default='hw1rUuTT', max_length=120),
        ),
    ]
